version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: despertador-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - despertador-network

networks:
  despertador-network:
    driver: bridge